### ISSUE TITLE
how to compare object instance when you use ParseAsDelegate

### ISSUE THREAD

**Issue by egarim** [davideicardi/DynamicExpresso#104]
lets said we have this case
  ```
class Customer
    {
        public string Name { get; set; }
        public int Age { get; set; }
        public char Gender { get; set; }
        public bool IsActive { get; set; }
        public Category Category { get; set; }
    }
    public class Category
    {
        public string Name { get; set; }
        public Category()
        {

        }
    }

```
then you have an object instance

```
Category Category = new Category() { Name = "Good" };
            var Customer = new Customer() { Name = "David", Age = 31, Gender = 'M', Category = Category };
```

how would you create an expression that uses comparison with object instances like this

`string whereExpression = $"customer.Age >= 31 && customer.Gender == 'M' && Category == {Category}";
`
the following code throws an exception

`Func<Customer, bool> dynamicWhere = interpreter.ParseAsDelegate<Func<Customer, bool>>(whereExpression, "customer")`

**Comment by davideicardi** [comment]
I think that you need to override `GetHashCode` and `Equals` on your class. See for example: https://grantwinney.com/how-to-compare-two-objects-testing-for-equality-in-c/
