### ISSUE TITLE
Support for interpolation ($ operator)

### ISSUE THREAD

**Issue by acds** [davideicardi/DynamicExpresso#107]
Hi

I'm trying to get DynamicExpresso to dynamically interpolate strings.

Say one has a configuration string that is defined as follows:
```json
{
 "myFormattedTemplate": "$\"{myObj.PropA}-{myObj.PropB}--{myObj.MySubObj.PropC.ToString()}\""
}
```

The config string `myFormattedTemplate` is considered safe and trusted. 
in C# Interpolated string generation is done at compile time, but the code at this time does not know the requisite format.

in C# I then want to dynamically generate the resultant string something like so:

```C#
class SubObj
{
    public int PropC { get; set;}
};

class SomeObj
{
    public string PropA { get; set;}
    public string PropA { get; set;}
    public SubObj MySubObj { get; set; } 
}

...

var someObj = new SomeObj() { PropA = "AAA", PropB = "BBB", MySubObj = new SubObj() { PropC = 102 };

var interpreter = new Interpreter().SetVariable("myObj", someObj);
var lambda = Interpreter.Parse(Configuration["myFormattedTemplate"]);

var formattedString = lambda.Invoke();
```

Where the result would be:
```
AAA-BBB--102
```

Seems DynamicExpresso does not currently support "$", I get an exception:
```
DynamicExpresso.Exceptions.ParseException: Syntax error '$' (at index 0).
   at DynamicExpresso.Parsing.Parser.NextToken()
   at DynamicExpresso.Parsing.Parser..ctor(ParserArguments arguments)
   at DynamicExpresso.Parsing.Parser.Parse(ParserArguments arguments)
   at DynamicExpresso.Interpreter.ParseAsLambda(String expressionText, Type expressionType, Parameter[] parameters)
   at DynamicExpresso.Interpreter.Parse(String expressionText, Type expressionType, Parameter[] parameters)
   at DynamicExpresso.Interpreter.Parse(String expressionText, Parameter[] parameters)
   at ...
```

**Comment by davideicardi** [comment]
Yes for now string interpolation is not supported. Of course any help to implement it is welcome ;-) ...

In the past I have solved this by using a regular expression replace. I extract each segment, like `myObj.PropA`, and just use dynamic expresso here, not on the full string.

You can use this replace method: https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.replace?view=netframework-4.7.2#System_Text_RegularExpressions_Regex_Replace_System_String_System_Text_RegularExpressions_MatchEvaluator_System_Int32_System_Int32_
