### ISSUE TITLE
.Net4 version throws "Argument types do not match"

### ISSUE THREAD

**Issue by larsmarkussen** [davideicardi/DynamicExpresso#108]
Hi

I've made a version build with .Net4 as i need this for some SSIS stuff
I made a few tweaks to the code to adapt to .net4, but nothing major.

Now i get the following error "Argument types do not match" 

The error is thrown no matter which expression i give it...
So now i wonder if there were a reson the .net4 support were removed? We used to use version 1.3, and that worked without problems

**Comment by davideicardi** [comment]
Hello @larsmarkussen ,
It was removed just for portability to .NET core... But not a technical reason. Also because at that time I was not very export on multi targeting...

If you are able to create a pull request I can try to investigate.
