### ISSUE TITLE
Pass expression as string to another func

### ISSUE THREAD

**Issue by umeshshende** [davideicardi/DynamicExpresso#110]
Trying to pass  **expression** as string  to another function which execute expression and return value in boolean **ie ifexpression function**

```
Func<string, string, string> replace = (str, repstr) => str.Replace("u", repstr);

var target1 = new Interpreter()
  .SetFunction("substring", substring)
  .SetFunction("replace", replace)
  .SetFunction("toLower", toLower)
  .SetFunction("toUpper", toUpper)
  .SetFunction("indexOf", indexOf);
Func<string, string, string, object> ifexpression =
  (str, str1, str2) => target1.Eval<bool>(str)?str1:str2;
var target = new Interpreter().SetFunction("ifexpression", ifexpression);
```

**Have expression like** 

```
// EXCEPTION OCCURED ON THIS EXPRESSION
var valuesss5 = target.Eval(
"ifexpression(\"replace(\"umesh\",\"S\") == \"Smesh\" \", \"shende\" , \"dilip\" )"
);
```

**Expected**
shende

**Actual**
```
DynamicExpresso.Exceptions.ParseException: '')' or ',' expected (at index 23).'
```

**Comment by davideicardi** [comment]
Not sure but I think that you are not using the right escaping. If you want to evaluate the string `"Hello world"` (with the double quote), you should pass the following expression: `"\"Hello world\""`. Now in your case you want to pass a string that contains other strings ... so you should escape the string passed to `ifexpression` but also the literals strings `\"umesh\"`, ...

In your example I think that the interpreter try to evaluate the following expression:
```
ifexpression("replace("umesh","S") == "Smesh" ", "shende" , "dilip" )
```

And you can see that it is wrong...

I think that you should write:
```
var valuesss5 = target.Eval(
"ifexpression(\"replace(\\\"umesh\\\",\\\"S\\\") == \\\"Smesh\\\" \", \"shende\" , \"dilip\" )"
);
```
