### ISSUE TITLE
Querying with enum

### ISSUE THREAD

**Issue by MuratGOZCU** [davideicardi/DynamicExpresso#113]
![OPERATOR](https://user-images.githubusercontent.com/31828822/64694520-78eb7c80-d4a2-11e9-9168-ed7217bfe096.png)

What is the problem in the code? Is anyone help

I have try the fallowing versions:

`condition = "condition.OperatorId == " + Operator.RightEqual;`

`Func<Condition, bool> dynamicWhere = interpreter.ParseAsDelegate<Func<Condition, bool>>(condition, "condition");`

`condition = "condition.OperatorId == " + Operator.RightEqual.ToString();`

`condition = "condition.OperatorId = " + Convert.ToInt32(Operator.RightEqual) ;`
`condition = "condition.OperatorId = " + Operator.RightEqual.ToString();`
`condition = "condition.OperatorId = " + Operator.RightEqual.ToString();`

**Comment by davideicardi** [comment]
I think that you must first add the `Operator` enum inside the interpreter like:
```
interpreter.Reference(typeof(Operator))
```

And then write a condition like:
```
condition = "condition.OperatorId == Operator.RightEqual";
```

**Comment by MuratGOZCU** [comment]
Thank you :)
@davideicardi
