### ISSUE TITLE
How to implement: "c == null"

### ISSUE THREAD

**Issue by 1448376744** [davideicardi/DynamicExpresso#115]
``` C#
 var interpreter = new Interpreter();
 var info = interpreter.DetectIdentifiers("c != null");
 var lambda = interpreter.Parse("c == null",new Parameter("c",typeof(string)));
 var result1 = lambda.Invoke(new Parameter("c", null,typeof(string)));
//throw exception....
```
Excuse me:
Is it safe to call the invoke function multiple times for the same lambda instance, and will the performance be improved?

**Comment by 1448376744** [comment]
I want to achieve such a function...

``` C#
<iftrue test="c==1">
</iftrue>
```

**Comment by davideicardi** [comment]
Yes, calling multiple times the `Invoke` function is fine, and it is suggested whenever possible. Your code seems to be correct. Write me if you see problems.

**Comment by 1448376744** [comment]
> Yes, calling multiple times the `Invoke` function is fine, and it is suggested whenever possible. Your code seems to be correct. Write me if you see problems.
``
//When c = null,Exceptions will occur
System.ArgumentNullException:“Value cannot be null. 
``

**Comment by 1448376744** [comment]
``` C#

            Expression<Func<int, bool>> expression = s => s < 1;
            var p = Expression.Parameter(typeof(int?), "s");
            var binary = Expression.MakeBinary(ExpressionType.Equal, p, Expression.Constant(null));
            var exp = Expression.Lambda(binary, p);
            var da = exp.Compile();
            var res = da.DynamicInvoke(new object[] { null});
```

Obviously, it can be realized

**Comment by davideicardi** [comment]
The problem is on how you construct the `Parameter` object. The constructor is defined as:
`public Parameter(string name, Type type, object value = null)`

So you should write: `new Parameter("c", typeof(string), null)`
