### ISSUE TITLE
Using DependecyInjection in custom methods

### ISSUE THREAD

**Issue by senkadir** [davideicardi/DynamicExpresso#116]
Hi,

I have a custom function in interpreter. 

I would like to connect to database with this function.

How can I use dependency injection in custom methods or in interpreter.

Any idea?

Example:

**Comment by davideicardi** [comment]
Maybe you can just pass to the interpreter a member function of a class that use dependency injection?

**Comment by senkadir** [comment]
It's a complex service making it. One service can reference multiple services. In each case, my transfer is difficult to manage. Is there a more general solution?

**Comment by davideicardi** [comment]
Sorry but I don't understand your doubts.
I have used dynamic expresso in a big application all wired with Dependency Injection without problems.
I just created the instance of the interpreter inside an injected service and I have passed to it all the required dependencies.

**Comment by senkadir** [comment]
Could you share little code piece to show injection system?

**Comment by davideicardi** [comment]
Here a general idea:

Suppose that you what to access within expression a service named `Foo`, with this interface:

```
interface Foo {
    string func1(string param1);
}
```

You can create an interpreter service that will use Dynamic Expresso `Interpreter` and get `Foo` service as an injected dependency:

```
class AppInterpreter {
    public AppInterpreter(Foo foo) {
        this.foo = foo;
    }

   public object Eval(String exp) {
      var target = new Interpreter().SetVariable("foo", this.foo);

      return target.Eval(exp);
   }
}
```

Now when you call `AppInterpreter.Eval` you can access the `Foo` service via the `foo` variable, so for example you can have an expression like `foo.func1("hello world")`.

**Comment by senkadir** [comment]
OK.

I thought same as you.

Thank you for answer.
