### ISSUE TITLE
Potential Concurrency Bugs

### ISSUE THREAD

**Issue by ppashakhanloo** [davideicardi/DynamicExpresso#118]
I believe I have found _two concurrency bugs_ in DynamicExpresso:

**A.** There is a race condition in the following function:
`System.Collections.Generic.IDictionary<System.String,DynamicExpresso.Identifier>.Item.set(System.String,DynamicExpresso.Identifier)`
when Thread 1 and Thread 2 both call `DynamicExpresso.Interpreter.SetIdentifier(DynamicExpresso.Identifier)`.

**B.** There is a race condition in the following functions:
Function 1: `System.Collections.Generic.IDictionary<System.String,DynamicExpresso.Identifier>.Item.set(System.String,DynamicExpresso.Identifier)`
Function 2: `System.Collections.Generic.IDictionary<System.String,DynamicExpresso.Identifier>.Item.TryGetVAlue(System.String,refDynamicExpresso.Identifier)`
when Thread 1 calls Function 1 from `DynamicExpresso.Interpreter.SetIdentifier(DynamicExpresso.Identifier)`
and Thread 2 calls Function 2 from
`DynamicExpresso.ParseArguments.TryGetIdentifier(System.String,outSystem.Linq.Expressions.Expression)`.

**Comment by davideicardi** [comment]
Yes, I think this is by "design" (or it is a design limit :smile: ) ). See https://github.com/davideicardi/DynamicExpresso#performance-and-multithreading

The idea is to optimize the library for evaluation of expression but I expect that the construction of the interpreter should be done just one time.

What is your scenario? Maybe you can do the initialization of the interpreter one time only?
