### ISSUE TITLE
Is it possible to restrict expression access to a given set of types and singletones?

### ISSUE THREAD

**Issue by OlegJakushkin** [davideicardi/DynamicExpresso#119]
Could you, please, provide an example of how one can limit and enforce that our expression only to be capable of calling methods of our class like to say `Test`, `Math.*` functions, create int/string types?

**Comment by davideicardi** [comment]
Inside an expression you can call any type that was previously referenced.
By default the following types are available:
https://github.com/davideicardi/DynamicExpresso#built-in-types-and-custom-types

You can add other types using `Reference` function. Or avoid loading default types using `InterpreterOptions` inside the `Interpreter` constructor.
