### ISSUE TITLE
The binary operator AndAlso is not defined for the types 'System.Nullable`1[System.Boolean]...

### ISSUE THREAD

**Issue by SaiedRahimy** [davideicardi/DynamicExpresso#121]
Hi dear friend
when execute like this command false&&(int?)null<10
This error occurs:
The binary operator AndAlso is not defined for the types 'System.Nullable`1[System.Boolean]' and 'System.Nullable`1[System.Int32]'.

I solved this error. I will be happy to send you the code to make your package better.
Thanks for your good package

**Comment by davideicardi** [comment]
Thanks! Open a Pull Request, to submit any chance.

**Comment by davideicardi** [comment]
Maybe fixed with #124 . Can you please check? Reopen if not yet fixed...
