### ISSUE TITLE
Expression to string and back to expression is not valid

### ISSUE THREAD

**Issue by cryo75** [davideicardi/DynamicExpresso#126]
I have the following code:

`            Expression<Func<PostCode, bool>> filter = (x => x.Code.Contains("1234") && x.City.Contains("York"));

            var s = filter.Body.ToString();
            //s = "x.Code.Contains(\"1234\") && x.City.Contains(\"York\")"; 

            var d = new Interpreter().ParseAsExpression<Func<PostCode, bool>>(s, "x");
`

Above, s evaluations to:

`x.Code.Contains("1234") AndAlso x.City.Contains("York")`

which will throw an exception when parsing back to expression. The commented string works fine.

What is the correct way to set up the expression to get it to parse correctly?

**Comment by cryo75** [comment]
Yes the problem is the mapping. So if one has a mapping for the operators it should work fine. I need this to pass the expression from client to server.

**Comment by davideicardi** [comment]
Maybe you can use this https://github.com/AgileObjects/ReadableExpressions ?
It seems to convert an expression to C# code, so you can probably use it with DynamicExpresso...

**Comment by cryo75** [comment]
I will give it a try
