### ISSUE TITLE
Parse function throws an System.Exception instead of ParseException.

### ISSUE THREAD

**Issue by AlexMazalov** [davideicardi/DynamicExpresso#128]
Hello,

I run the line of code: 
    Lambda parsedExpression = new Interpreter().Parse("1+1*");

And expected an exception with type ParseException, but caught with type System.Exception:
     "System.InvalidOperationException: The binary operator Multiply is not defined for the types 'System.Int32' and 'System.Void'."

**Comment by davideicardi** [comment]
I have tried to provide a fix in PR #129 . What do you think?

**Comment by AlexMazalov** [comment]
That is great, thanks!
