### ISSUE TITLE
Error free code does not work

### ISSUE THREAD

**Issue by Eikosa** [davideicardi/DynamicExpresso#130]
![image](https://user-images.githubusercontent.com/20538090/100809424-21d71c00-3447-11eb-93fa-188481a8a184.png)

**Comment by bortolin** [comment]
This work for me:

"demene#asd".Split('#')[1]

**Comment by Eikosa** [comment]
I was actually using a string as a separator

**Comment by davideicardi** [comment]
So it was not a bug right? I'm closing the issue.
