### ISSUE TITLE
ParseLiteralDecimalNumberStyle

### ISSUE THREAD

**Issue by rkaderli** [davideicardi/DynamicExpresso#133]
I had errors parsing scientific formatted numbers. How about adding NumberStyles.AllowExponent to Parser?

private const NumberStyles ParseLiteralDecimalNumberStyle = NumberStyles.AllowLeadingSign | NumberStyles.AllowDecimalPoint | NumberStyles.AllowExponent;

**Comment by davideicardi** [comment]
These options are currently defined inside the `Parser` class ([link](https://github.com/davideicardi/DynamicExpresso/blob/master/src/DynamicExpresso.Core/Parsing/Parser.cs#L27)) but are anot configurable.

Maybe we can add a specific configuration for that. Any help/PR is appreciated ;-)
