### ISSUE TITLE
Global functions chained with linq causes parse exceptions from 2.5.0

### ISSUE THREAD

**Issue by weltall** [davideicardi/DynamicExpresso#148]
So in these days, I've updated from 2.3.1 to 2.6.0 and some specific test cases in my own test suite started failing.

Upon bisecting it seems 2.5.0 is causing those test cases to fail so I made a test unit and tried it on both 2.4.1 and 2.5.0 and I can reliably see it failing due to a parse exception in 2.5.0 while it worked fine in 2.4.1.

From a c# standpoint, the syntax is correct, though.

This is the test case that can show the wrong behaviour and it seems likely related to #144 

```
		[Test]
		public void Func_Global_Invocation()
		{
			Func<object[], double, double, object[]> subArray = (entries, skipFirst, skipLast) => entries.Take(entries.Length - (int)skipLast).Skip((int)skipFirst).ToArray();

			var target = new Interpreter();

			target.SetVariable("arr1", new object[] { 1d, 2d, 3d });
			target.SetFunction("SubArray", subArray);

			Assert.AreEqual(2, target.Eval("SubArray(arr1, 1, 1).First()"));
		}
```

On 2.4.1 this works fine the eval returns 2 and the test succeeds. in 2.5.0 upward this will return a parse exception (for note this is a checkout of the current master to have a recollection of lines references)

```
  Message: 
    DynamicExpresso.Exceptions.ParseException : Syntax error (at index 20).
  Stack Trace: 
    Parser.ValidateToken(TokenId t, String errorMessage) line 2474
    Parser.Parse() line 68
    Parser.Parse(ParserArguments arguments) line 24
    Interpreter.ParseAsLambda(String expressionText, Type expressionType, Parameter[] parameters) line 443
    Interpreter.Parse(String expressionText, Type expressionType, Parameter[] parameters) line 343
    Interpreter.Eval(String expressionText, Type expressionType, Parameter[] parameters) line 420
    Interpreter.Eval(String expressionText, Parameter[] parameters) line 397
    OtherTests.Func_Global_Invocation() line 104
```

**Comment by davideicardi** [comment]
Thanks for the bug report. I think it is related to #138.
I will try to investigate, but any help is as usual appreciated ;-)

**Comment by weltall** [comment]
Some initial debugging seems to hint that it's eating entirely the .First() part of the expression when parsing.

**Comment by davideicardi** [comment]
What if you just write something simpler like:

```
		[Test]
		public void Func_Global_Invocation()
		{
			Func<object[], object[]> subArray = (entries) => entries;

			var target = new Interpreter();

			target.SetVariable("arr1", new object[] { 1d, 2d, 3d });
			target.SetFunction("SubArray", subArray);

			Assert.AreEqual(new object[] { 1d, 2d, 3d }, target.Eval("SubArray(arr1)"));
			Assert.AreEqual(1d, target.Eval("SubArray(arr1).First()"));
		}
```

?

Just to try to limit the scope of the problem...

**Comment by weltall** [comment]
The first case is working fine (subarray(arr1)) the second case (subarray(arr1).first()) goes in exception

```
  Message: 
    DynamicExpresso.Exceptions.ParseException : Syntax error (at index 14).
  Stack Trace: 
    Parser.ValidateToken(TokenId t, String errorMessage) line 2474
    Parser.Parse() line 68
    Parser.Parse(ParserArguments arguments) line 24
    Interpreter.ParseAsLambda(String expressionText, Type expressionType, Parameter[] parameters) line 443
    Interpreter.Parse(String expressionText, Type expressionType, Parameter[] parameters) line 343
    Interpreter.Eval(String expressionText, Type expressionType, Parameter[] parameters) line 420
    Interpreter.Eval(String expressionText, Parameter[] parameters) line 397
    OtherTests.Func_Global_Invocation2() line 118
```

**Comment by davideicardi** [comment]
Thanks, very strange. I will try to look at it, but not sure when.

@metoule do you have some idea of what can be wrong? (sorry to always ask to you ;-) , or course do what you can)

**Comment by metoule** [comment]
The fix was an easy one: the parsing was stopped after a call to the registered function (i.e. the `.First()` part was ignored). That triggered a `ParserException`, because the parser expects the expression to have reached the end.

**Comment by davideicardi** [comment]
Version 2.6.1 released with the fix! Thank you @metoule for the fix and @weltall for bug report!
