### ISSUE TITLE
Really Awesome!

### ISSUE THREAD

**Issue by Michael-DST** [davideicardi/DynamicExpresso#29]
I really wish Github had a "kudos" feature. :)  Just wanted to send you some appreciation for this library!  I had some terrible evaluation code that was based on ASP.NET databinding from back in the day... YUCK.  You just saved me a ton of work. :)

I will be using this in my framework, FYI!  Thanks again.  Please feel free to close this issue once you see it.

**Comment by davideicardi** [comment]
Thank you! I really appreciate your comment!
