### ISSUE TITLE
Formula with SI Units

### ISSUE THREAD

**Issue by bcachet** [davideicardi/DynamicExpresso#37]
Hello,

First of all, a huge thanks for this library. It's awesome.

I need to parse formula of this kind: `"3mm + 1cm"`
Values have Physical Dimensions/Units.

I already have libraries that perform +,-,*,/ operations on objects with Dimension support (https://github.com/anjdreas/UnitsNet, https://github.com/objorke/QuantityTypes).
These libraries are also able to create Dimensioned object from string.

Is there already a way to do this or to add this support ?

I was thinking of:
- Replacing Physical Units contained in the formula by Variables that I will pass to the Interpreter.
- Adding a ParserArguments.Settings to indicate that we want to parse Numbers (IntegerLiteral/RealLiteral) as value with Physical Dimension representation (PhysicalValueLiteral)
  In this case, IntegerLiteral & RealLiteral will be parsed using ParsePhysicalValueLiteral instead of ParseIntegerLiteral/ParseRealLiteral.

What is your opinion on this usage ?

**Comment by bcachet** [comment]
Hello,

My first proposition (replacing physical units by variables I pass to the Interpreter) is a nightmare. 
I will investigate the second option.
If you have any advice on how to/where to perform the modfications, I will be glad to hear.

Have a nice day

**Comment by davideicardi** [comment]
Hello,

One idea that I already have is to support some kind of pluggable extensions.
Maybe some class that you can pass to the Interpreter that will be called each time the parser try to parse something (methods, numbers, ...).
In this case I will more than happy to integrate this feature.

Another idea maybe is to just run some kind of regular expression before calling the parser that simply convert all `3mm` to `new Dimension("3mm")` or similar.

What do you think?

davide

P.S. Just consider also that now that [Roslyn scripting api](http://www.jayway.com/2015/05/09/using-roslyn-to-build-a-simple-c-interactive-script-engine/) are available maybe you should also consider it as a completely different option. Probably more future proof ...

**Comment by bcachet** [comment]
The approach, by converting `3mm` to `new Quantity("3mm")` is almost what I did when trying to replace physical units by variables I pass to the Interpreter.
But units can be tricky: `m/s`, `ms-1`, `km/s`

I think your extension support can be really interesting. We will earn the power of your library to generate AST and then we choose which library to use to parse remaining values.

Any hint on how to do this ?

**Comment by bcachet** [comment]
Thanks a lot for the Roslyn link
It's `System.CodeDom.Compiler` on steroids. Maybe for my usage `CodeDom` is enough, not really sure I need to analysis generated code. I am not really sure I am able to plug from the generated Syntax Tree.
