### ISSUE TITLE
Indexed property setter not working

### ISSUE THREAD

**Issue by mono-software** [davideicardi/DynamicExpresso#39]
Hi, can anything be done about the indexed property setter not working. In both examples below the following exception occurs:

An unhandled exception of type 'System.ArgumentException' occurred in System.Core.dll.
Additional information: Expression must be writeable

Code:

`var interpreter = new Interpreter();

```
        var arr = new[] { 1 };
        arr[0] = 2;
        interpreter.SetVariable("arr", arr);
        interpreter.Eval("arr[0] = 3");

        var list = new List<int>(new[] { 1 });
        list[0] = 2;
        interpreter.SetVariable("list", list);
        interpreter.Eval("list[0] = 3");`
```

Thanks.

**Comment by davideicardi** [comment]
I will try to look at this problem in the following days... Thanks for the feedback

**Comment by davideicardi** [comment]
Here unit tests that can be used to test this feature:

		[Test]
		public void GitHub_Issue_39_Simple_Reassignment()
		{
			var target = new Interpreter().SetVariable("x", 3);
			Assert.AreEqual(3, target.Eval("x"));

			target.Eval("x = 23");

			Assert.AreEqual(23, target.Eval("x"));
		}

		[Test]
		public void GitHub_Issue_39_Array_Reassignment()
		{
			var arr = new[] { 1 };
			arr[0] = 2;
			var target = new Interpreter().SetVariable("arr", arr);
			Assert.AreEqual(2, target.Eval("arr[0]"));

			target.Eval("arr[0] = 3");

			Assert.AreNotEqual(2, target.Eval("arr[0]"));
			Assert.AreEqual(3, target.Eval("arr[0]"));
		}

		[Test]
		public void GitHub_Issue_39_List_Reassignment()
		{
			var list = new List<int>(new[] { 1 });
			list[0] = 2;
			var target = new Interpreter().SetVariable("list", list);
			Assert.AreEqual(2, target.Eval("list[0]"));

			target.Eval("list[0] = 3");

			Assert.AreNotEqual(2, target.Eval("list[0]"));
			Assert.AreEqual(3, target.Eval("list[0]"));
		}
