### ISSUE TITLE
Adding some more operations

### ISSUE THREAD

**Issue by mala29** [davideicardi/DynamicExpresso#40]
The compiler works all fine. But i would like to know if the power operator, increment and decrement operators are not required ? If they are required I would like to contribute the same. Please let me know asap

**Comment by davideicardi** [comment]
Increment (++) and decrement (--) can probably added without more problems. Other operators, like power, as I know are [not available in C#](http://stackoverflow.com/questions/3034604/is-there-an-exponent-operator-in-c) and I try to use a standard C# syntax.

If you want to add some operators I appreciate any pull request!

**Comment by mala29** [comment]
Hello,

I was trying to run the project(Dynamic Expresso) but i encountered the
error which read "NUnit.Framework.Assert does not contain definition for
throws".
Can you help me fix this ?

Regards,
Mala Gupta,
M.Sc. Software Engineering,
PSG College of Technology.

**Comment by davideicardi** [comment]
That is strange ... what compiler do you use? Do you have manually restored nuget packages or automatically?

**Comment by mala29** [comment]
I am using c# in visual studio. At first we encountered 541 errors and then
downloaded nuget packages (core,framework,nmock) and added these to the
references. Latter we were left with 10 errors.
I hereby, attach the screenshot of the errors.
Direct us in any possible way.

PFA.

**Comment by davideicardi** [comment]
Visual Studio >= 2013 shuld automatically restore (download) missing nuget packages. Are you sure to have nuget configured correctly? Probably you have used a wrong package. But I sugget to just use the auto restore feature: 
https://docs.nuget.org/consume/package-restore#automatic-package-restore-in-visual-studio

**Comment by mala29** [comment]
We are using visual studio 2013 and all the packages are properly
installed. I would like to know where do I find the code for all the basic
operators already done like addition,  subtraction, etc.
