### ISSUE TITLE
Roslyn ~ DynamicExpresso

### ISSUE THREAD

**Issue by jonathh21** [davideicardi/DynamicExpresso#41]
Question...

Hi, I started looking at your solution here, but following your comment in your FAQ stating that if possible one should use Rosyln, one should.. I am doing just that.

However, one thing I have found dead easy using DynamicExpresso is that I defined 'this' using SetVariable("this", this);

and I am easily able to use 'this.' in my 'Formula'

I am struggling to do this in Roslyn, any pointers?

Thanks.

**Comment by davideicardi** [comment]
Yes, you are right. I'm suspect that `this` is a reserved keyword in Roslyn. I think that you should use another keyword. Why not using `it`, or `current` or something similar...

davide
