### ISSUE TITLE
Unable to evaluate expression if a number starts with a `.` (dot)

### ISSUE THREAD

**Issue by sgokuladas** [davideicardi/DynamicExpresso#43]
The interpreter cannot evaluate a formula if I say interpreter.evaluate("1 + .2")

Note:  interpreter.evaluate("1 + **0**.2") works

**Comment by sgokuladas** [comment]
I'm new around here, but I'll give it a go if I get some time next week




On Mon, Jun 20, 2016 at 11:57 PM +1000, "Davide Icardi" <notifications@github.com<mailto:notifications@github.com>> wrote:


You are right, this is a bug. I added this is my todo list but I don't know when I can work on it.
Eventually I appreciate any help (pull request).

-

**Comment by JustinRChou** [comment]
Solution might not be as clean without changing more code.

**Comment by davideicardi** [comment]
Fixed, thanks to @JustinRChou
