### ISSUE TITLE
Possible to transform the parsed expression?

### ISSUE THREAD

**Issue by ryanackley** [davideicardi/DynamicExpresso#53]
Great project. I'm using it to parse queries in a REST api I'm developing. Currently, I'm using ParseAsExpression to just pass through a user's query to EntityFramework LINQ query.

What I want to do is have a separate model for my API than I do for EF. So instead of returning EF models from my API I want to have DTO's (Data Transfer Objects) that provide a user-friendly view of my data.  

What I want is to parse an expression using the DTO classes but then somehow turn that into an expression that uses the EF classes. Is this even feasible?

**Comment by davideicardi** [comment]
Hello, @ryanackley 
I think it is possible but there are many possible solutions.

If you generate the expression (see .NET Expression class) using DynamicExpresso using DTO objects then you can probably manipulate it and "convert" to EF classes. It is probably not so easy but ...

What is the difference between EF and DTO classes? Just the type or also the properties are different?
