### ISSUE TITLE
Nested dynamic objects

### ISSUE THREAD

**Issue by kendarorg** [davideicardi/DynamicExpresso#54]
Given a nested dynamic object

`dynamic dyn = new ExpandoObject();
dyn.Sub = new ExpandoObject();
dyn.Sub.Foo = "bar";`

calling 

`Eval("dyn.Sub.Foo")`

will not recognize the Foo variable

**Comment by davideicardi** [comment]
Thanks for bug report and fix 👍 ! I will merge it now...

**Comment by davideicardi** [comment]
Fix merged
