### ISSUE TITLE
.ToString should be called automatically for string concatenation

### ISSUE THREAD

**Issue by asdfgasdfsafgsdfa** [davideicardi/DynamicExpresso#58]
In C# we can do:

`string text = "abc" + 123;` which results in a single string `"abc123"`.

However the following does not work:

		public class Unit
		{
			public string Name = "Test";
			public int Age = 123;
		}

	DynamicExpresso.Interpreter interpreter = new DynamicExpresso.Interpreter(
				DynamicExpresso.InterpreterOptions.CommonTypes |
				DynamicExpresso.InterpreterOptions.SystemKeywords |
				DynamicExpresso.InterpreterOptions.PrimitiveTypes);

		interpreter.Reference(typeof(Func<>));

		string code = "u.Name + u.Age";

		var function = interpreter.ParseAsDelegate<Func<Unit, string>>(code, "u");

		var text = function.Invoke(new Unit());

If `code` is changed to `u.Name + u.Age.ToString()` everything works perfectly, so I guess it has to do with casting u.Age to an object before passing it to string.Concat?

**Comment by davideicardi** [comment]
Sorry for the late response (I have probably missed the notification). You are right, this can be an useful improvement. I will evaluate it for the future. Of course any help is appreciated :wink:
