### ISSUE TITLE
Support all integer literals

### ISSUE THREAD

**Issue by Piedone** [davideicardi/DynamicExpresso#62]
Like "u" for unsigned, e..g `4u` (being equivalent to `(uint)4`). See: https://msdn.microsoft.com/en-us/library/aa664674(v=vs.71).aspx

**Comment by davideicardi** [comment]
Yes, that would be possible. I will add the feature in my TODO list, of course any help is appreciated 😃

**Comment by Piedone** [comment]
Thank you.

**Comment by QoL15155** [comment]
Its been over 5 years. Is the enhancement still on the "TODO list"?
