### ISSUE TITLE
Using DynamicExpresso with Xamarin

### ISSUE THREAD

**Issue by mazloumi** [davideicardi/DynamicExpresso#63]
Hi, I tried to install the package in a Xamarin project but got an error. Any thoughts?

Attempting to gather dependency information for package 'DynamicExpresso.Core.1.3.3.5' with respect to project 'Newton.iOS', targeting 'Xamarin.iOS,Version=v1.0'
  GET https://www.nuget.org/api/v2/Packages(Id='DynamicExpresso.Core',Version='1.3.3.5')
  OK https://www.nuget.org/api/v2/Packages(Id='DynamicExpresso.Core',Version='1.3.3.5') 220ms
Total number of results gathered : 98
Gathering dependency information took 239.7 ms
Summary of time taken to gather dependencies per source :
https://www.nuget.org/api/v2/	-	221.25 ms
/Users/lynas/Downloads	-	3.52 ms
Attempting to resolve dependencies for package 'DynamicExpresso.Core.1.3.3.5' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'DynamicExpresso.Core.1.3.3.5'
Resolved actions to install package 'DynamicExpresso.Core.1.3.3.5'
Retrieving package 'DynamicExpresso.Core 1.3.3.5' from 'Official NuGet Gallery'.
  GET https://www.nuget.org/api/v2/package/DynamicExpresso.Core/1.3.3.5
  OK https://www.nuget.org/api/v2/package/DynamicExpresso.Core/1.3.3.5 674ms
Acquiring lock for the installation of DynamicExpresso.Core 1.3.3.5
Acquired lock for the installation of DynamicExpresso.Core 1.3.3.5
Installing DynamicExpresso.Core 1.3.3.5.
Completed installation of DynamicExpresso.Core 1.3.3.5
For adding package 'DynamicExpresso.Core.1.3.3.5' to project 'App.iOS' that targets 'xamarinios10'.
Install failed. Rolling back...
Package 'DynamicExpresso.Core.1.3.3.5' does not exist in project 'App.iOS'
Package 'DynamicExpresso.Core.1.3.3.5' does not exist in folder '/Users/me/Projects/app.git/packages'
Executing nuget actions took 971.49 ms
Could not install package 'DynamicExpresso.Core 1.3.3.5'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by davideicardi** [comment]
For now dynamic expresso is available only for .net 4.5. We are working to
port it on other .net versions, there are some branches that you can use as
a starting point...
