### ISSUE TITLE
How to make it recognizes members uses `new` modifier?

### ISSUE THREAD

**Issue by AbdoDabbas** [davideicardi/DynamicExpresso#66]
I'm using  `Dynamic Expresso` library to evaluate c# expression dynamically.
I inherited from a class and used `new Modifier` to hide a member like this:  

    public class MyClass : MyClassAbstract {  
    public Dictionary<string, object> dict;
    public new object this[string name]  
        {  
         get { return dict[name]; }
        }  
    }

So when I try to evaluate the following:  

    var parsed = interpreter.ParseAsDelegate<Func<MyClass, bool>>("X[\"key1\"]","X");
    
This one wil throw an exception that `MyClass` doesn't support indexer by name.  
Although `MyClassAbstract` contains `this[string name]` in it.

**Comment by davideicardi** [comment]
I'm not able to reproduce it.
I have tried with this unit test:

		public abstract class MyClassAbstract
		{
			public object this[string name]
			{
				get
				{
					return null;
				}
			}
		}

		public class MyClass : MemberInvocationTest.MyClassAbstract
		{
			public new object this[string name]
			{
				get { return "hello"; }
			}
		}

		[Test]
		public void TestIndexer_Overwrite()
		{
			var target = new Interpreter();
			var parsed = target.ParseAsDelegate<Func<MyClass, object>>("X[\"key1\"]", "X");

			Assert.AreEqual("hello", parsed(new MyClass()));
		}

It seems to work fine. Can you provide me a full code to reproduce it.
