### ISSUE TITLE
Is there a way to speedup the evaluation process ?

### ISSUE THREAD

**Issue by AbdoDabbas** [davideicardi/DynamicExpresso#67]
Hi,
I'm using :
`Func<MyClass, MyClass, bool> evalFunc;  
evalFunc = interpreter.ParseAsDelegate<Func<MyClass, MyClass, bool>>(expression1, "X", "Y");  
evalFunc.Invoke(itemX, itemY);
`
On a large number of items and there're multiple expressions I pass depending on a condition.
Is there a way that I compile the expression and cache it ? to not take a lot of time when `ParseAsDelegate` it.

Or any other advice to speed up the process ?

I may apply this on 20,000 items.\

Regards.

**Comment by AbdoDabbas** [comment]
I solved it by parsing the expressions before start iterating over the large amount of items I have.
I speed up the process significantly, what do you think of implementing caching mechanism inside the lib it self ?

**Comment by davideicardi** [comment]
Yes, implementing cache internally can be a solution but can have some disadvantages. For now caching it externally it is quite easy because you can do on your app based on your specific needs.

See also this:
https://github.com/davideicardi/DynamicExpresso#performance-and-multithreading

davide
