### ISSUE TITLE
Setting variable named "bool": SetVariable("bool","value")

### ISSUE THREAD

**Issue by JobaDiniz** [davideicardi/DynamicExpresso#69]
I can set a variable like `SetVariable("bool","value")` but when I use `Eval("bool")` an error occurs.
I know I know, `bool` it's a reserved word in c# but that fact that I can `SetVariable` named *bool* implies I could use it.

Is there a workaround?

**Comment by davideicardi** [comment]
Yes, you are right. I think that the `SetVariable` should validate the name and do not permit this operation.
I will try to fix it in the future, but as usual any help is appreciated 😄

**Comment by davideicardi** [comment]
After some further investigation on this issue I discovered that it is a little complex to use the same rules of C#. In C# `bool`, `true`, `false`, `is`, ... are reserved keywords. Other are just types, like `Int32`. So for example you can avtually create a variable in C# called `Int32` but not `int`.

Within Dynamic Expresso the only "real" reserved keywords are `is`, `as`, `new` and `typeof` (see `LanguageConstants.ReservedKeywords`). All the types (`bool`, `int`, `Int32`, ...) are just "constant".

For now I have decided to not permit any variables name that match `LanguageConstants.ReservedKeywords`. All other names can be overwritten. I have then changed the order of priority between identifiers (variables) and known types (references) inside the parser. 
So for now you should actually be able to create a variable using `SetVariable("bool", "value")`.

In real case scenarios try to use variables names with a more ubiquitous name to reduce possible conflict for the future.
