### ISSUE TITLE
ExpandoObject Property Comparison Problem

### ISSUE THREAD

**Issue by bberberoglu** [davideicardi/DynamicExpresso#72]
Given a dynamic object to evaluate comparison 
```
dynamic obj= new ExpandoObject();
obj.AppVersion = 010101;

// throws InvalidOperationException (...operator was not defined for types 'System.Object' and 'System.Int32'.)
Eval("obj.AppVersion > 010101") 
```

- Workaround Solution : In expression, use explicit cast

```
Eval("((int)obj.AppVersion) > 010101") 
```

- Permanent Solution(Parser.cs)
Before comparison methods, change left expression result type to right expression with "Expression.ConvertChecked" method.

```
Expression GenerateGreaterThanEqual(Expression left, Expression right)
{
if (left.Type == typeof(string))
	{
		return Expression.GreaterThanOrEqual(
			GenerateStaticMethodCall("Compare", left, right),
			Expression.Constant(0)
		);
	}

	left = Expression.ConvertChecked(left, right.Type);
        return Expression.GreaterThanOrEqual(left, right);
}
```

**Comment by davideicardi** [comment]
Thanks very much for the feedback. I will evaluate this. 
My concern is that this solution can break some other expression... one case that I can think is comparing an int16 to an int32 ... This can potentially generate a convert expection but I think that the comparison should succeed...
 
All the unit tests are passing?

**Comment by bberberoglu** [comment]
Thanks for reply.
you're right, maybe create a generic class which is responsible to convertion, and handle convertion exceptions. Also this convertion part only execute for parameters which are inherided from dynamic object.

Unit test results;
![image](https://user-images.githubusercontent.com/8998960/35663865-82a53e78-0730-11e8-9c58-4b1c944b433d.png)

**Comment by davideicardi** [comment]
I have investigate further this topic.
The problem seems to be that for now only a small subset of operations over dynamic objects are supported. Basically currently only property and method invocations are supported, all other operations (comparison, unary and binary operations, conversions, ...).

Here some other tests that for now doesn't pass:

		[Test]
		public void Call_method_using_dynamic_parameter()
		{
			dynamic dyn = new ExpandoObject();
			dyn.Foo = 5;

			var interpreter = new Interpreter()
				.SetVariable("dyn", (object)dyn);

			Assert.AreEqual(Math.Pow(dyn.Foo, 2), interpreter.Eval("Math.Pow(dyn.Foo, 2)"));
		}

		[Test]
		public void Comparison_with_dynamic_properties()
		{
			dynamic dyn = new ExpandoObject();
			dyn.Foo = 500;

			var interpreter = new Interpreter()
				.SetVariable("dyn", (object)dyn);

			Assert.AreEqual(dyn.Foo == 500, interpreter.Eval("dyn.Foo == 500"));
			Assert.AreEqual(500 == dyn.Foo, interpreter.Eval("500 == dyn.Foo"));

			Assert.AreEqual(dyn.Foo != 200, interpreter.Eval("dyn.Foo != 200"));
			Assert.AreEqual(200 != dyn.Foo, interpreter.Eval("200 != dyn.Foo"));

			Assert.AreEqual(dyn.Foo > 200, interpreter.Eval("dyn.Foo > 200"));
			Assert.AreEqual(600 > dyn.Foo, interpreter.Eval("600 > dyn.Foo"));

			Assert.AreEqual(dyn.Foo < 600, interpreter.Eval("dyn.Foo < 600"));
			Assert.AreEqual(200 < dyn.Foo, interpreter.Eval("200 < dyn.Foo"));

			Assert.AreEqual(dyn.Foo >= 500, interpreter.Eval("dyn.Foo >= 500"));
			Assert.AreEqual(500 >= dyn.Foo, interpreter.Eval("500 >= dyn.Foo"));

			Assert.AreEqual(dyn.Foo <= 500, interpreter.Eval("dyn.Foo <= 500"));
			Assert.AreEqual(500 <= dyn.Foo, interpreter.Eval("500 <= dyn.Foo"));
		}

Solving this I think will require a full support on dynamic types. I will leave this issue open if someone can work on it in the future.
