### ISSUE TITLE
Decimal literal not working if number doesn't have dot

### ISSUE THREAD

**Issue by sanmigueljpco** [davideicardi/DynamicExpresso#78]
Hi, I'm trying to evaluate a simple expression. Unfortunately I'm not able to make this expression work. "500m>500m". It's throwing an error saying not valid integer literal. But what I really want is the expresso treat it as decimal since both numbers have "m" literal. Is it possible to make it work using your library?

**Comment by davideicardi** [comment]
Yes, you are right. Unfortunately for now this expression is not supported. I will try to solve this issue soon.

For now I think that you should write `500.0m`.
