### ISSUE TITLE
Investigate issue on functions overloads

### ISSUE THREAD

**Issue by davideicardi** [davideicardi/DynamicExpresso#81]
See https://stackoverflow.com/questions/50967956/dynamicexpresso-setfunction-not-working-with-method-overload

```
[Test]
public static void TestInterpreter()
{
    var interpreter = new Interpreter();

    Func<decimal, decimal> roundFunction1 = (userNumber) => Round(userNumber);
    Func<decimal, int, decimal> roundFunction2 = (userNumber, decimals) => Round(userNumber, decimals);
    Func<string, string, int> charindexFunction1 = (toFind, userString) => Charindex(toFind, userString);
    Func<string, string, int, int> charindexFunction2 = (toFind, userString, offset) => Charindex(toFind, userString, offset);

    interpreter.SetFunction("ROUND", roundFunction1);
    interpreter.SetFunction("ROUND", roundFunction2);
    interpreter.SetFunction("CHARINDEX", charindexFunction1);
    interpreter.SetFunction("CHARINDEX", charindexFunction2);

    var importe = 666.66M;
    interpreter.SetVariable("ImporteTotal", importe);

    var textoAlbaran = "ALBARAN-01";
    interpreter.SetVariable("Albaran", textoAlbaran);

    Assert.AreEqual(Round(importe), interpreter.Eval("ROUND(ImporteTotal)"));
    Assert.AreEqual(Round(importe, 1), interpreter.Eval("ROUND(ImporteTotal, 1)"));
    Assert.AreEqual(Charindex("BARAN", textoAlbaran), interpreter.Eval("CHARINDEX(\"BARAN\", Albaran"));
    Assert.AreEqual(Charindex("BARAN", textoAlbaran, 2), interpreter.Eval("CHARINDEX(\"BARAN\", Albaran, 2)"));
}

public static decimal Round(decimal userNumber)
{
    return Math.Round(userNumber);
}

public static decimal Round(decimal userNumber, int decimals)
{
    return Math.Round(userNumber, decimals);
}

public static int Charindex(string toFind, string userString)
{
    return userString.IndexOf(toFind);
}

public static int Charindex(string toFind, string userString, int offset)
{
    return userString.IndexOf(toFind, offset);
}
```

**Comment by davideicardi** [comment]
I have investigated the issue. The problem is that `interpreter.SetFunction` replace the previous value. So if you call `SetFunction` 2 or more times the last call overwrite the previous one. If I write:

````
interpreter.SetFunction("ROUND", roundFunction2);
interpreter.SetFunction("ROUND", roundFunction1);
````

Only `roundFunction1` will be registered.
Unfortunately changing this logic is quite difficult...
I have created a new issue #82 to enable this functionality for the future.

Here some possible workarounds:

1. Use different function names:
````
interpreter.SetFunction("ROUND2", roundFunction2);
interpreter.SetFunction("ROUND1", roundFunction1);
````
Maybe not very clean but it should work

2. Register a type instead of a function.
Create an helper class like:
````
public static class Helpers // you can use any name here ...
{
	public static decimal Round(decimal userNumber)
	{
		return Math.Round(userNumber);
	}
	public static decimal Round(decimal userNumber, int decimals)
	{
		return Math.Round(userNumber, decimals);
	}
}
````
Register it using `interpreter.Reference(typeof(Helpers));` and use it inside expression by calling `Helpers.Round(...)`.
Consider that if you want to use a different case you can just use `InterpreterOptions.CaseInsensitive`, so you can write `HELPERS.ROUND(...)`.

3. Combine 1 and 2. For example you can register the most common name directly but also register the helper. So if you need to call the function with only 1 parameter you can call `ROUND(x)` or `Helpers.ROUND(x)`, but if you need to call the more "advanced" function you must call `Helpers.ROUND(x, y)`.

What do you think? In my opinion solution 2 is the best ...

**Comment by Gonzo345** [comment]
Hi there! You didn't only found the origin of the problem, you even offered 3 ways to apply a workaround! I will give this a try and will wait for the enhancement whenever it comes to release! 😃  Congratulations for this awesome work again ❤️
