### ISSUE TITLE
Net core. Is assembly creating ? 

### ISSUE THREAD

**Issue by Diaskhan** [davideicardi/DynamicExpresso#85]
Net core platform doesnt provide unloading assemlies! If assembly is loaded its not unloading in futute.

Could u tell me when evaluating a script is assembly is creating ? 

Need for long runing app, if the many scripts are generated, gc will clean not used scripts ?

**Comment by Diaskhan** [comment]
I want to use this engine in that kind case 
https://docs.camunda.org/manual/7.4/user-guide/process-engine/expression-language/

**Comment by davideicardi** [comment]
Hello,
No, Dynamic Expresso doesn't generate assemblies. It is based on .NET `Expression` class that will do all the work in memory.

https://docs.microsoft.com/en-us/dotnet/api/system.linq.expressions.expression?view=netframework-4.7.2

**Comment by Diaskhan** [comment]
1.What about pass object as variable ? to call there methods ?
2.Supporting net core 2 ?

**Comment by davideicardi** [comment]
1. Yes, it is possible. See documentation for details, `SetVariable`.
2. Available platforms: .NET Core 2.0, .NET 4.6.1

**Comment by Diaskhan** [comment]
what about Dynamic objects ?
its possible to pass dynamic objects ?

**Comment by davideicardi** [comment]
Yes, there is a partial support for dynamic objects. See readme.md and issues for details.
