### ISSUE TITLE
a + b when a is of type Nullable<double> and b is of type Int32

### ISSUE THREAD

**Issue by nike61** [davideicardi/DynamicExpresso#88]
Can't find solution to make this work properly:
```
interpreter.SetVariable("a", 1, typeof(int));
interpreter.SetVariable("b", 1.2, typeof(double?));
var q = interpreter.Eval("a + b");
```
I'm getting
> System.InvalidOperationException: "The binary operator Add is not defined for the types 'System.Int32' and 'System.Nullable`1[System.Double]'."

**Comment by davideicardi** [comment]
This code compile using standard C#? I usually try to reproduce the C# behaviour. If this should work I will make this a bug and try to find a solution...

**Comment by nike61** [comment]
@davideicardi Yes, this code works properly:
```
int a = 1;
double? b = 1.2;
var c = a + b; // returns 2.2
```
Standard .NET Core console app

**Comment by davideicardi** [comment]
Ok, I mark this issue as a bug. I will try to fix it, but of course any help is appreciated :wink:

**Comment by nike61** [comment]
@davideicardi the problem is that the code try to call:
```
private static Expression GenerateAdd(Expression left, Expression right)
{
      return Expression.Add(left, right);
}
```
And there is no defined operation "Add" between int and Nullable<double>. The same is discussing here I guess:
https://stackoverflow.com/questions/7027384/the-binary-operator-add-is-not-defined-for-the-types-system-string-and-syste
In this post they use Add(Expression, Expression, MethodInfo) overload and define method that provied Add

**Comment by nike61** [comment]
@davideicardi please check my PR
