### ISSUE TITLE
User params keyword in function

### ISSUE THREAD

**Issue by tqmitaca** [davideicardi/DynamicExpresso#95]
Hi,
I will use function with number of parameters variable. (functions like max(), min(),..)
I tried     Func< int[], int> Max = (v) => myMax( v ), but it crash on execution.
I tried     Func< patrams int[], int> Max = (v) => myMax( v ), but it does not compile.

 private int myMax(params int[] v)
        {
            int m = -1;
            foreach (int i in v)
                if (m < i)
                    m = i;

            return m;
        }

Best regards
Giovanni Rubagotti

**Comment by davideicardi** [comment]
Thanks for the report. Can I just ask you to provide a unit test that show the problem? So it can be easier to understand and fix it.

Try to look at other tests for some examples.

Thanks

**Comment by tqmitaca** [comment]
Thanks for the quick reply.

I resolved this issue using a custom delegate:

delegate int MyDelegate(params int[] p);

var target = new Interpreter();
target.SetFunction("max", new MyDelegate(myMax));

var result = target.Eval("max(1,2,3,4,5,6)");

Best regards
Giovanni Rubagotti
