### ISSUE TITLE
Why use roslyn instead of DE

### ISSUE THREAD

**Issue by arkypita** [davideicardi/DynamicExpresso#96]
Ciao Davide and congratulations for the work you did.
I am working on an interpreter of formulas for a scada program.

In the project description you say:

> Below you can find a list of some similar projects that I have evaluated or that can be interesting to study. 
> For one reason or another none of these projects exactly fit my needs so I decided to write my own interpreter.
> 
> - Roslyn Project - Scripting API - https://github.com/dotnet/roslyn/wiki/Scripting-API-Samples
> 	- This is the new Microsoft Official Compiler as a service library. I suggest to consider using Roslyin instead of DynamicExpresso whenever possible.

What are the needs that convinced you to write your own interpreter? Can I ask you for what reasons do you advise to use roslyn instead of DynamicExpresso? 

Best regards, Diego

**Comment by davideicardi** [comment]
Ciao Diego,
When I started DynamicExpresso Roslyn was not yet available, this is the primary historical difference.

No Roslyn has many more features (of course) so it is probably a better alternative for complex use cases. Maybe DynamicExpresso is still a better alternative for very simple use case.
